FROM golang:1.20

WORKDIR /app

# copy go.mod go.sum ./
# RUN go mod download
#COPY ALL FILE TO THE APP DIRECTORY
# COPY utils cmd internal ./
COPY  .  ./


# ENV DB_USER=ichat\
#     DB_PASSWORD=password\
#     DB_HOST=db\
#     DB_NAME=ichat\
#     PORT=8080

# #build the app


RUN go run ./cmd/migrate/migrate.go
RUN go build -o ./bin ./cmd/main.go
EXPOSE 8080



CMD ["./bin"]

## use linux 
# FROM alpine:latest

# WORKDIR /app
# COPY --from=build ./bin .
# EXPOSE 8080
# CMD ["./app"]

