version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: ichat
      DB_PASSWORD: password
      DB_HOST: mysql
      PORT: 8080
      DB_PORT: 3305
      DB_NAME: ichat

  db:
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ichat 
      MYSQL_USER: ichat
      MYSQL_PASSWORD: password 
      
